// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolLibrary.Infrastructure.Data;

#nullable disable

namespace SchoolLibrary.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260801101054_ReplaceLocalPathsWithR2Storage")]
    partial class ReplaceLocalPathsWithR2Storage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SchoolLibrary.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Name = "Теория"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Name = "Задачи"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Name = "Презентации"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Name = "Тестове"
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            Name = "Проекти"
                        },
                        new
                        {
                            Id = new Guid("ffffffff-ffff-ffff-ffff-ffffffffffff"),
                            Name = "Работни листове"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"),
                            Name = "Подготовка за изпит"
                        });
                });

            modelBuilder.Entity("SchoolLibrary.Domain.Entities.GradeLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("GradeLevels", t =>
                        {
                            t.HasCheckConstraint("CK_GradeLevels_Number", "[Number] BETWEEN 5 AND 12");
                        });

                    b.HasData(
                        new
                        {
                            Id = 5,
                            Number = 5
                        },
                        new
                        {
                            Id = 6,
                            Number = 6
                        },
                        new
                        {
                            Id = 7,
                            Number = 7
                        },
                        new
                        {
                            Id = 8,
                            Number = 8
                        },
                        new
                        {
                            Id = 9,
                            Number = 9
                        },
                        new
                        {
                            Id = 10,
                            Number = 10
                        },
                        new
                        {
                            Id = 11,
                            Number = 11
                        },
                        new
                        {
                            Id = 12,
                            Number = 12
                        });
                });

            modelBuilder.Entity("SchoolLibrary.Domain.Entities.Resource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ArchivedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("AudienceType")
                        .HasColumnType("int");

                    b.Property<string>("Author")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CoverStorageKey")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("ExternalUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("FileContentType")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileStorageKey")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("OriginalFileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("IsArchived");

                    b.HasIndex("SubjectId");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("SchoolLibrary.Domain.Entities.ResourceGradeLevel", b =>
                {
                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("GradeLevelId")
                        .HasColumnType("int");

                    b.HasKey("ResourceId", "GradeLevelId");

                    b.HasIndex("GradeLevelId");

                    b.ToTable("ResourceGradeLevels");
                });

            modelBuilder.Entity("SchoolLibrary.Domain.Entities.ResourceSchoolClass", b =>
                {
                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SchoolClassId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ResourceId", "SchoolClassId");

                    b.HasIndex("SchoolClassId");

                    b.ToTable("ResourceSchoolClasses");
                });

            modelBuilder.Entity("SchoolLibrary.Domain.Entities.SchoolClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("GradeLevelId")
                        .HasColumnType("int");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("Id");

                    b.HasIndex("GradeLevelId", "Section")
                        .IsUnique();

                    b.ToTable("SchoolClasses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000001"),
                            GradeLevelId = 5,
                            Section = "а"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000001"),
                            GradeLevelId = 6,
                            Section = "а"
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000001"),
                            GradeLevelId = 7,
                            Section = "а"
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000001"),
                            GradeLevelId = 8,
                            Section = "а"
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000002"),
                            GradeLevelId = 8,
                            Section = "б"
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000003"),
                            GradeLevelId = 8,
                            Section = "в"
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000004"),
                            GradeLevelId = 8,
                            Section = "г"
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000001"),
                            GradeLevelId = 9,
                            Section = "а"
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000002"),
                            GradeLevelId = 9,
                            Section = "б"
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000003"),
                            GradeLevelId = 9,
                            Section = "в"
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000004"),
                            GradeLevelId = 9,
                            Section = "г"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            GradeLevelId = 10,
                            Section = "а"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            GradeLevelId = 10,
                            Section = "б"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            GradeLevelId = 10,
                            Section = "в"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            GradeLevelId = 10,
                            Section = "г"
                        },
                        new
                        {
                            Id = new Guid("11000000-0000-0000-0000-000000000001"),
                            GradeLevelId = 11,
                            Section = "а"
                        },
                        new
                        {
                            Id = new Guid("11000000-0000-0000-0000-000000000002"),
                            GradeLevelId = 11,
                            Section = "б"
                        },
                        new
                        {
                            Id = new Guid("11000000-0000-0000-0000-000000000003"),
                            GradeLevelId = 11,
                            Section = "в"
                        },
                        new
                        {
                            Id = new Guid("11000000-0000-0000-0000-000000000004"),
                            GradeLevelId = 11,
                            Section = "г"
                        },
                        new
                        {
                            Id = new Guid("12000000-0000-0000-0000-000000000001"),
                            GradeLevelId = 12,
                            Section = "а"
                        },
                        new
                        {
                            Id = new Guid("12000000-0000-0000-0000-000000000002"),
                            GradeLevelId = 12,
                            Section = "б"
                        },
                        new
                        {
                            Id = new Guid("12000000-0000-0000-0000-000000000003"),
                            GradeLevelId = 12,
                            Section = "в"
                        },
                        new
                        {
                            Id = new Guid("12000000-0000-0000-0000-000000000004"),
                            GradeLevelId = 12,
                            Section = "г"
                        });
                });

            modelBuilder.Entity("SchoolLibrary.Domain.Entities.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Математика"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Информатика"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Name = "Информационни технологии"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Name = "Физика и астрономия"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Name = "Български език и литература"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Name = "Английски език"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Name = "Немски език"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            Name = "Химия и опазване на околната среда"
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            Name = "Биология и здравно образование"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-1111-1111-1111-111111111111"),
                            Name = "История и цивилизации"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-1111-1111-1111-111111111111"),
                            Name = "География и икономика"
                        });
                });

            modelBuilder.Entity("SchoolLibrary.Domain.Entities.Resource", b =>
                {
                    b.HasOne("SchoolLibrary.Domain.Entities.Category", "Category")
                        .WithMany("Resources")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolLibrary.Domain.Entities.Subject", "Subject")
                        .WithMany("Resources")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("SchoolLibrary.Domain.Entities.ResourceGradeLevel", b =>
                {
                    b.HasOne("SchoolLibrary.Domain.Entities.GradeLevel", "GradeLevel")
                        .WithMany("ResourceGradeLevels")
                        .HasForeignKey("GradeLevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolLibrary.Domain.Entities.Resource", "Resource")
                        .WithMany("ResourceGradeLevels")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GradeLevel");

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("SchoolLibrary.Domain.Entities.ResourceSchoolClass", b =>
                {
                    b.HasOne("SchoolLibrary.Domain.Entities.Resource", "Resource")
                        .WithMany("ResourceSchoolClasses")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolLibrary.Domain.Entities.SchoolClass", "SchoolClass")
                        .WithMany("ResourceSchoolClasses")
                        .HasForeignKey("SchoolClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Resource");

                    b.Navigation("SchoolClass");
                });

            modelBuilder.Entity("SchoolLibrary.Domain.Entities.SchoolClass", b =>
                {
                    b.HasOne("SchoolLibrary.Domain.Entities.GradeLevel", "GradeLevel")
                        .WithMany("SchoolClasses")
                        .HasForeignKey("GradeLevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GradeLevel");
                });

            modelBuilder.Entity("SchoolLibrary.Domain.Entities.Category", b =>
                {
                    b.Navigation("Resources");
                });

            modelBuilder.Entity("SchoolLibrary.Domain.Entities.GradeLevel", b =>
                {
                    b.Navigation("ResourceGradeLevels");

                    b.Navigation("SchoolClasses");
                });

            modelBuilder.Entity("SchoolLibrary.Domain.Entities.Resource", b =>
                {
                    b.Navigation("ResourceGradeLevels");

                    b.Navigation("ResourceSchoolClasses");
                });

            modelBuilder.Entity("SchoolLibrary.Domain.Entities.SchoolClass", b =>
                {
                    b.Navigation("ResourceSchoolClasses");
                });

            modelBuilder.Entity("SchoolLibrary.Domain.Entities.Subject", b =>
                {
                    b.Navigation("Resources");
                });
#pragma warning restore 612, 618
        }
    }
}
